import '../styles/global.scss';
import { HeaderPublic } from '@/common/components/header-public';

export const metadata = {
  title: 'EventApp',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pl">
      <body>
        <HeaderPublic />
        {children}
      </body>
    </html>
  )
}
